#!/bin/bash

VER=$1
SUB=$2

rm -f repack_zip/emp/zImage
rm -f repack_zip/system/lib/modules/*.ko

if [ ! -d repack_zip/system ]; then
	mkdir repack_zip/system
	mkdir repack_zip/system/lib
	mkdir repack_zip/system/lib/modules
    mkdir repack_zip/system/lib/modules/qca_cld
fi

mv arch/arm64/boot/Image.gz-dtb repack_zip/emp/zImage
cat repack_zip/emp/dtbdump_1.dtb >> repack_zip/emp/zImage
cat repack_zip/emp/dtbdump_2.dtb >> repack_zip/emp/zImage
cat repack_zip/emp/dtbdump_3.dtb >> repack_zip/emp/zImage
cat repack_zip/emp/dtbdump_4.dtb >> repack_zip/emp/zImage
find -name "*.ko" -exec mv {} repack_zip/system/lib/modules \;
repack_zip/emp/strip --strip-unneeded repack_zip/system/lib/modules/*
mv repack_zip/system/lib/modules/wlan.ko repack_zip/system/lib/modules/qca_cld/qca_cld_wlan.ko

cd repack_zip
zip -r kernel.zip *
mv kernel.zip ../
cd ..
