#!/bin/bash

VER=$1
SUB=$2

rm -f repack_zip/emp/zImage
rm -f repack_zip/emp/*.dtb
rm -f magisk_module/system/lib/modules/*.ko

if [ ! -d magisk_module/system ]; then
	mkdir magisk_module/system
	mkdir magisk_module/system/lib
	mkdir magisk_module/system/lib/modules
    mkdir magisk_module/system/lib/modules/qca_cld
fi

mv arch/arm64/boot/Image.gz-dtb repack_zip/emp/zImage
mv arch/arm/boot/dts/qcom/msm8996-sharp-pa32-v3-pmi8996-fluid.dtb repack_zip/emp/dtbdump_1.dtb
mv arch/arm/boot/dts/qcom/msm8996-sharp-pa32-v2-fluid.dtb repack_zip/emp/dtbdump_2.dtb
mv arch/arm/boot/dts/qcom/msm8996-sharp-pa32-v3-fluid.dtb repack_zip/emp/dtbdump_3.dtb
mv arch/arm/boot/dts/qcom/msm8996-sharp-pa32-v2-pmi8996-fluid.dtb repack_zip/emp/dtbdump_4.dtb
cat repack_zip/emp/dtbdump_1.dtb >> repack_zip/emp/zImage
cat repack_zip/emp/dtbdump_2.dtb >> repack_zip/emp/zImage
cat repack_zip/emp/dtbdump_3.dtb >> repack_zip/emp/zImage
cat repack_zip/emp/dtbdump_4.dtb >> repack_zip/emp/zImage
find -name "*.ko" -exec mv {} magisk_module/system/lib/modules \;
repack_zip/emp/strip --strip-unneeded magisk_module/system/lib/modules/*
mv magisk_module/system/lib/modules/wlan.ko magisk_module/system/lib/modules/qca_cld/qca_cld_wlan.ko

cd repack_zip
zip -r kernel.zip *
mv kernel.zip ../
cd ../magisk_module
zip -r PA32_EMP_Kernel_modules_magisk.zip *
mv PA32_EMP_Kernel_modules_magisk.zip ../
cd ..
echo "--------------------------------------------------"
echo "-              Repack      Completed             -"
echo "--------------------------------------------------"
echo "-              kernel  by rote66                 -"
echo "--------------------------------------------------"
echo "-Cutting Edge Aftermarket Sharp Phone Technology-"
echo "--------------------------------------------------"
